zynqmp-dpsub-y := zynqmp_disp.o zynqmp_dpsub.o zynqmp_dp.o zynqmp_kms.o
obj-$(CONFIG_DRM_ZYNQMP_DPSUB) += zynqmp-dpsub.o
xlnx-tpg-objs := xlnx_tpg.o
xlnx-tpg-$(CONFIG_DRM_XLNX_BRIDGE_VTC) += xlnx_vtc_list.o
obj-$(CONFIG_DRM_XLNX_TPG) += xlnx-tpg.o
obj-$(CONFIG_DRM_XLNX_BRIDGE_VTC) += xlnx_vtc.o
